configure deploy - add task with echo ls

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -127,6 +127,29 @@ steps:
         echo doit
         echo  SHow IN OTHER STAGE the output variable terraform_plan_exitcode  is "$(terraformplan.terraform_plan_exitcode)"
         echo echo terraform apply "./out_plan_file"
+
+        #OUTPUT=$(terraform apply "./out_plan_file -var environment="${BRANCH_NAME}" -input=false -detailed-exitcode)
+        OUTPUT=$(ls -l out_plan_file ;pwd)
+              OUT=$?
+              echo "the terraform plan exitcode is $OUT"
+              #OUT=2 # force it for testing
+              if [ $OUT -eq 0 ];then
+                  echo "No changes. Infrastructure is up-to-date!"
+                  sleep 1
+              elif [ $OUT -eq 1 ];then
+                  echo "Terraform planned has failed!"
+                  sleep 1
+                  exit 1
+              elif [ $OUT -eq 2 ];then
+                  echo "Changes have been noticed!"
+                  echo "##vso[task.setvariable variable=terraform_plan_exitcode;isOutput=true]$OUT"
+                  sleep 1
+                  terraform show ./out_plan_file
+              else
+                  echo "Terraform planned has failed!"
+                  exit 1
+              fi
+    name: terraformapply
                     
   # - task: AWSShellScript@1
   #     condition: eq(stageDependencies.Build.Terraform_Plan.outputs['TerraformPLanVar.terraform_plan_exitcode'], '2')
