change plan file dir and add checkov again

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -268,35 +268,35 @@ steps:
     name: tflint_rstudio
 
 
-    # try checkov
-    - task: AWSShellScript@1
-      inputs:
-        awsCredentials: 'aws-AzureDevopsiamuser'
-        regionName: $(TF_VAR_region)
-        arguments: '$(TF_VAR_rstudio_app_name) $(TF_VAR_region) $(BRANCH_NAME)'
-        scriptType: 'inline'
-        inlineScript: |
-          echo args are $1 $2 $3
-          export TF_VAR_rstudio_app_name=$1
-          export TF_VAR_region=$2
-          export BRANCH_NAME=$3
-          cd "${BRANCH_NAME}/${TF_VAR_rstudio_app_name}"/ || exit
-          echo pwd is $PWD        
-          echo "STARTING checkov for checking scripts in dir $BRANCH_NAME/${TF_VAR_rstudio_app_name} "
-          ls -la
-          echo install with pip install checkov
-          pip install checkov
+  # try checkov
+  - task: AWSShellScript@1
+    inputs:
+      awsCredentials: 'aws-AzureDevopsiamuser'
+      regionName: $(TF_VAR_region)
+      arguments: '$(TF_VAR_rstudio_app_name) $(TF_VAR_region) $(BRANCH_NAME)'
+      scriptType: 'inline'
+      inlineScript: |
+        echo args are $1 $2 $3
+        export TF_VAR_rstudio_app_name=$1
+        export TF_VAR_region=$2
+        export BRANCH_NAME=$3
+        cd "${BRANCH_NAME}/${TF_VAR_rstudio_app_name}"/ || exit
+        echo pwd is $PWD        
+        echo "STARTING checkov for checking scripts in dir $BRANCH_NAME/${TF_VAR_rstudio_app_name} "
+        ls -la
+        echo install with pip install checkov
+        pip install checkov
 
-          checkov -d .
-          # RCLINT=$?
-          # if [ $RCLINT != 0 ]
-          # then
-          #   echo "tflint reports an error in $BRANCH_NAME/${TF_VAR_rstudio_app_name}"
-          #   exit 1
-          # else
-          #   echo "All is fine for tflint to continu for $BRANCH_NAME/${TF_VAR_rstudio_app_name}."
-          # fi
-      name: checkov_rstudio
+        checkov -d .
+        # RCLINT=$?
+        # if [ $RCLINT != 0 ]
+        # then
+        #   echo "tflint reports an error in $BRANCH_NAME/${TF_VAR_rstudio_app_name}"
+        #   exit 1
+        # else
+        #   echo "All is fine for tflint to continu for $BRANCH_NAME/${TF_VAR_rstudio_app_name}."
+        # fi
+    name: checkov_rstudio
 
   # terraform init
   - task: AWSShellScript@1
