onlysteps

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -94,7 +94,27 @@ steps:
         cd "${BRANCH_NAME}"/ || exit
         echo pwd is $PWD        
         echo "STARTING TERRAFORM PLAN"
-        terraform plan
+        # terraform plan
+
+        OUTPUT=$(terraform plan -out="./out_plan_file" -var environment="${_BRANCH_NAME}" -input=false -detailed-exitcode)
+              OUT=$?
+              echo "the terraform plan exitcode is $OUT"
+              #OUT=2 # force it for testing
+              if [ $OUT -eq 0 ];then
+                  echo "No changes. Infrastructure is up-to-date!"
+                  sleep 1
+              elif [ $OUT -eq 1 ];then
+                  echo "Terraform planned has failed!"
+                  sleep 1
+                  exit 1
+              elif [ $OUT -eq 2 ];then
+                  echo "Changes have been noticed!"
+                  sleep 1
+                  terraform show ./out_plan_file
+              else
+                  echo "Terraform planned has failed!"
+                  exit 1
+              fi
     name: terraformplan
   # - template: ADO/DEV-plan.yml@Templates
   
