move if to task 13

diff --git a/preps/azure-pipelines.yml b/preps/azure-pipelines.yml
--- a/preps/azure-pipelines.yml
+++ b/preps/azure-pipelines.yml
@@ -100,15 +100,15 @@ jobs:
               exit 1
           fi
 
-          if [[ -d "$_LIVE_DIR" ]]; then
-              if [[ ! -f "${_LIVE_DIR}/${_BACKEND_TPL}" ]]; then
-                  echo "[ERROR] The file backend.tf.tpl doesn't exist - $_BACKEND_TPL"
-                  exit 1
-              fi
-          else
-              echo "[ERROR] The supplied live directory doesn't exist - $_LIVE_DIR"
-              exit 1
-          fi
+          # if [[ -d "$_LIVE_DIR" ]]; then
+          #     if [[ ! -f "${_LIVE_DIR}/${_BACKEND_TPL}" ]]; then
+          #         echo "[ERROR] The file backend.tf.tpl doesn't exist - $_BACKEND_TPL"
+          #         exit 1
+          #     fi
+          # else
+          #     echo "[ERROR] The supplied live directory doesn't exist - $_LIVE_DIR"
+          #     exit 1
+          # fi
 
           if [[ -z "$TF_VAR_app_name" ]]; then
               echo "[ERROR] Must set TF_VAR_app_name environment variable"
