move if to task 17

diff --git a/preps/azure-pipelines.yml b/preps/azure-pipelines.yml
--- a/preps/azure-pipelines.yml
+++ b/preps/azure-pipelines.yml
@@ -75,7 +75,7 @@ jobs:
           export TF_VAR_region=${{parameters.TF_VAR_region}}
           export TERRAFORM_VERSION="1.0.5"
           # set -x  # debug
-          # set -e
+          # set -e   ==>  -e  Exit immediately if a command exits with a non-zero status.   Don't use it here because terraform plan is used with exit codes.
           # set -o pipefail
           LIVE_DIR=${LIVE_DIR:="live"}
           # _BACKEND_TPL=${BACKEND_TPL:="backend.tf.tpl"}
@@ -136,26 +136,22 @@ jobs:
           echo test >>testfile.txt
           ls -l testfile.txt
           OUTPUT=$(terraform plan -var environment="${_BRANCH_NAME}" -input=false -detailed-exitcode)
-                EXCODE=$?
-                echo excode=$EXCODE
-                ls -l
-                cat backend.tf
-                # OUT=$?
-                # echo "the var OUT is $OUT"
-                # #OUT=2 # force it for testing
-                # if [ $OUT -eq 0 ];then
-                #     echo "No changes. Infrastructure is up-to-date!"
-                #     sleep 1
-                # elif [ $OUT -eq 1 ];then
-                #     echo "Terraform planned has failed!"
-                #     sleep 1
-                #     exit 1
-                # elif [ $OUT -eq 2 ];then
-                #     echo "Changes have been noticed!"
-                #     sleep 1
-                #     terraform show ./out_plan_file
-                # else
-                #     echo "Terraform planned has failed!"
-                #     exit 1
-                # fi
-      name: terraform_apply
+                OUT=$?
+                echo "the var OUT is $OUT"
+                #OUT=2 # force it for testing
+                if [ $OUT -eq 0 ];then
+                    echo "No changes. Infrastructure is up-to-date!"
+                    sleep 1
+                elif [ $OUT -eq 1 ];then
+                    echo "Terraform planned has failed!"
+                    sleep 1
+                    exit 1
+                elif [ $OUT -eq 2 ];then
+                    echo "Changes have been noticed!"
+                    sleep 1
+                    terraform show ./out_plan_file
+                else
+                    echo "Terraform planned has failed!"
+                    exit 1
+                fi
+      name: terraform_plan
