move if to task 7

diff --git a/preps/azure-pipelines.yml b/preps/azure-pipelines.yml
--- a/preps/azure-pipelines.yml
+++ b/preps/azure-pipelines.yml
@@ -122,23 +122,23 @@ jobs:
           terraform init
           echo "END TERRAFORM INIT"
           echo "STARTING OUTPUT VARIABLE"
-          OUTPUT=$(terraform plan -out="./out_plan_file" -var environment="${_BRANCH_NAME}" -input=false -detailed-exitcode)
-          OUT=$?
-          echo "the var OUT is $OUT"
-          #OUT=2 # force it for testing
-          if [ $OUT -eq 0 ];then
-              echo "No changes. Infrastructure is up-to-date!"
-              sleep 1
-          elif [ $OUT -eq 1 ];then
-              echo "Terraform planned has failed!"
-              sleep 1
-              exit 1
-          elif [ $OUT -eq 2 ];then
-              echo "Changes have been noticed!"
-              sleep 1
-              terraform show ./out_plan_file
-          else
-              echo "Terraform planned has failed!"
-              exit 1
-          fi
+          # OUTPUT=$(terraform plan -out="./out_plan_file" -var environment="${_BRANCH_NAME}" -input=false -detailed-exitcode)
+          # OUT=$?
+          # echo "the var OUT is $OUT"
+          # #OUT=2 # force it for testing
+          # if [ $OUT -eq 0 ];then
+          #     echo "No changes. Infrastructure is up-to-date!"
+          #     sleep 1
+          # elif [ $OUT -eq 1 ];then
+          #     echo "Terraform planned has failed!"
+          #     sleep 1
+          #     exit 1
+          # elif [ $OUT -eq 2 ];then
+          #     echo "Changes have been noticed!"
+          #     sleep 1
+          #     terraform show ./out_plan_file
+          # else
+          #     echo "Terraform planned has failed!"
+          #     exit 1
+          # fi
       name: terraform_apply
